### ISSUE TITLE
Guido Van Rossum & the forbidding of tabs, source?

### ISSUE THREAD

**Issue by pzelnip** [yaml/www.yaml.org#103]
https://yaml.org/faq.html says:

    Indeed Guido van Rossum of Python has acknowledged that allowing TABs in Python source is a headache for many people and that were he to design Python again, he would forbid them.

I would be interested in knowing the source of that reference, as often tabs are suggested as useful for those who are visually impaired ([src](https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/), [src](https://dev.to/alexandersandberg/why-we-should-default-to-tabs-instead-of-spaces-for-an-accessible-first-environment-101f)), and I can find no reference in Googling that Guido has indicated Python ideally should not support tabs.

In fact [this link](https://legacy.python.org/search/hypermail/python-1994q2/0205.html) from the Python mailing list indicates that Guido generally supports them (or at least did in the early days -- that's quite old).

**Comment by ingydotnet** [comment]
I believe that @clarkevans wrote that (about 20 years ago).
