### ISSUE TITLE
Rename repo to 'www.yaml.org'

### ISSUE THREAD

**Issue by ingydotnet** [yaml/www.yaml.org#13]
We already have a `www.yaml.com` and soon a `www.yaml.io`.

I'll have to make sure the server that serves yaml.org gets updated. Doubt this would break anything else. GitHub should handle redirects anyway.

**Comment by adamvoss** [comment]
Looks like this have been done and the issue can be closed :-)

**Comment by kenliten** [comment]
close this issue, it looks like it is done.

**Comment by ingydotnet** [comment]
Closing.
