### ISSUE TITLE
Host yaml.org on this repo's gh-pages branch

### ISSUE THREAD

**Issue by ingydotnet** [yaml/www.yaml.org#14]
http://yaml.org is currently hosted on a cloud vm. It used to be needed because there were cgi programs like ypaste, but ypaste is now hosted elsewhere.

yaml.org is all static so we can host on GitHub.

The following steps should happen:
1. Set up a Makefile rule to build the content into gh-pages
2. Get the yaml/yaml-spec to also build in gh-pages
3. Test the gh-pages site using some other domain
4. Write a `Contributing` file explaining how new content should be added
5. Set CNAME to `yaml.org`
6. Work with Clark to update the yaml.org DNS

After this, it will be much easier to maintain yaml.org and have changes get published.

**Comment by adamvoss** [comment]
FYI, you could setup a Travis CI build to automate build the site and publishing to the gh-pages branch since you won't be able to used GitHub Pages because of custom scripts.

**Comment by MartinDelille** [comment]
I'll be happy to help!

**Comment by ingydotnet** [comment]
All good now.
