### ISSUE TITLE
Please add strictyaml to yaml.org

### ISSUE THREAD

**Issue by david-libremone** [yaml/www.yaml.org#17]
<a href="https://pypi.python.org/pypi/strictyaml">strictyaml</a> is a Python-based YAML parser based on `ruamel.yaml`. It provides Python-based schema validation and parses a restricted subset of YAML (design rationale given here <https://github.com/crdoconnor/strictyaml/blob/master/FAQ.rst>).

**Comment by perlpunk** [comment]
Added
