### ISSUE TITLE
Wrong link in http://yaml.org/spec/

### ISSUE THREAD

**Issue by BartolomeSintes** [yaml/www.yaml.org#35]
The link to the 1.0 spec in http://yaml.org/spec/ is wrong:
Current html
<dt>
              <span class="term">
          2004-01-29 (final draft YAML 1.0)
        </span>
            </dt>
            <dd>
              <a href="/spec/1.1/index.html" target="_top">html</a>
            </dd>
It should be:
<dt>
              <span class="term">
          2004-01-29 (final draft YAML 1.0)
        </span>
            </dt>
            <dd>
              <a href="/spec/1.0/index.html" target="_top">html</a>
            </dd>

**Comment by ingydotnet** [comment]
Fixed. Thanks.
