### ISSUE TITLE
http://yaml.org/spec/current.html yields v1.1 spec instead of v1.2

### ISSUE THREAD

**Issue by javabrett** [yaml/www.yaml.org#40]
http://yaml.org/spec/current.html :
```
YAML Ain't Markup Language (YAML™) Version 1.1
```
I can't see the source for this, so it may be an old file that needs deleting off the server, or an old configuration/deployment path/alias which needs updating.

Noticed this when a forum linked to `current.html` and noticed this was old.

**Comment by perlpunk** [comment]
It also seems that current.html is a link to an older draft of 1.1.
@ingydotnet can we add a redirect to 1.2 here?

**Comment by ingydotnet** [comment]
@perlpunk done in b8206fb
