### ISSUE TITLE
active maintenance of yaml.org

### ISSUE THREAD

**Issue by ssbarnea** [yaml/www.yaml.org#58]
Apparently the website maintenance reached a status which counts as unmaintained as the list of trivial open PRs not merged is a proof of that.

I would like to address this issue and assure that yaml.org does not look like a relic.

@ingydotnet @clarkevans @orenbenkiki Can you help me fix that?

**Comment by MartinDelille** [comment]
I'll be happy to help!

**Comment by ingydotnet** [comment]
Fixed. All PRs applied or closed.
