### ISSUE TITLE
JvYaml link is broken, and the project doesn't seem to exist anywhere

### ISSUE THREAD

**Issue by MyApaulogies** [yaml/www.yaml.org#59]
I tried searching up the project, and every site I found just pointed to <a href="http://www.oracle.com/splash/java.net/maintenance/index.html">this link.</a> A quick ctrl-f on the relocated projects Oracle page tells you that it's not anywhere in there, either.

**Comment by perlpunk** [comment]
hm, yeah. But I found this: https://mvnrepository.com/artifact/net.java.dev/jvyaml

**Comment by perlpunk** [comment]
I moved the link to a HTML comment
