### ISSUE TITLE
User Contribution: the alleged official logo

### ISSUE THREAD

**Issue by GwynethLlewelyn** [yaml/www.yaml.org#66]
AFAIK, this is the official logo for YAML, so I did an SVG version of the PNG, and set it to the public domain. There are gazillions of 'YAML logos' out there, but the only one I found directly on a YAML official page was this one, so I'm assuming it's the right one to use...

Zipped because, well, GitHub dislikes SVG.
[YAML-logo.svg.zip](https://github.com/yaml/www.yaml.org/files/5086171/YAML-logo.svg.zip)

(Edit: after validating this SVG, I got an error on the W3C validator, so I uploaded a new version)

**Comment by ingydotnet** [comment]
@GwynethLlewelyn Thank you for doing that.

That's the preferred logo. The only fitting place on the site I could think of to put it was as the favicon for all pages.

Done! See 9deaa7b

**Comment by GwynethLlewelyn** [comment]
I'm glad it was useful :-)
