### ISSUE TITLE
Design proposal

### ISSUE THREAD

**Issue by fippli** [yaml/www.yaml.org#67]
Hi! I work as a web developer/designer and would like to contribute in any way I can. Here is a start of a design proposal for the website. Please give feedback and let me know if this is interesting.

<img width="1440" alt="Screen Shot 2020-08-27 at 11 12 24" src="https://user-images.githubusercontent.com/2800451/91423644-188f4f80-e859-11ea-97cc-6c6391115b54.png">

**Comment by kenliten** [comment]
The first thing on my mind when take a look on the website, was, "God! What the heck is this?", and inmediately thought "we can improve this web and make it look awesome".

And, now, being honest your design is pretty cool, it looks very nice, but, I believe the community is trying to keep that 'old school' style, however it would be wonderful to be part of the web's remake, I can help with html, js or css.

**Comment by ingydotnet** [comment]
Thanks but we're fine to leave yaml.org in its current form for now. Other web efforts are actively in progress.
