### ISSUE TITLE
Request to add FusionYAML to the list of libraries

### ISSUE THREAD

**Issue by BrokenEarthDev** [yaml/www.yaml.org#68]
Dear Staff,

I'm requesting to add fusionyaml (a java project) to the list of libraries.

### **Info:**
**Implemented YAML version(s):** 1.0, 1.1
**How completely implemented is it:** almost completely implemented, with the exception of anchors. Writing comments aren't supported but reading comments are
**Project Website:** https://www.fusionyaml.org/
**Programming Language:** Java
**Small Note:** Depends on SnakeYAML to deliver the best features

Thanks in advance

**Comment by ingydotnet** [comment]
https://www.fusionyaml.org/ is gone. Closing.
