### ISSUE TITLE
Registering an application/yaml Media Type

### ISSUE THREAD

**Issue by cjaccino** [yaml/www.yaml.org#75]
YAML has become widely used as a more human-friendly alternative to JSON.  Given its widespread use, I was surprised to find no media type registration at IANA.  There is also a need for a structured data suffix, +yaml, to formally legitimize media types that are syntactically valid YAML, but also provide semantics.  

For IANA registration, someone close enough to the YAML format authoring should submit some paperwork to the IETF (or possibly directly to IANA).  I would be happy to provide the bulk of the content for the registration of the media type and the +yaml structured data suffix if someone here would be willing to represent the "owners" of the YAML format.

Happy to provide more info, use cases, etc, if needed.

**Comment by ingydotnet** [comment]
This website is only for publishing yaml.org website.
YAML is specified here https://github.com/yaml/yaml-spec/
Related: https://github.com/yaml/yaml-spec/issues/49
