### ISSUE TITLE
The faq.html page that detailed the preferred extension is now a 404

### ISSUE THREAD

**Issue by olivierlefloch** [yaml/www.yaml.org#85]
Historically it seems the main source of information for the yaml / yml debate was the FAQ page, for example on the Wikipedia page for YAML:

https://en.wikipedia.org/wiki/YAML#cite_note-11

It seems with the Github Pages version of the website, this page has been removed, and I can't find documentation on the preferred filename extension for YAML either on the yaml.org website or in the RFCs. Perhaps the faq.html page could be restored?

**Comment by ingydotnet** [comment]
Yep. I'll take care of that. We've been busy getting https://yaml.org/spec/1.2.2/ out but now I can fix the broken stuff in yaml.org.

It's all in the git repo somewhere :)
