### ISSUE TITLE
Link to snakeyaml website shows a football team page in indonesian?

### ISSUE THREAD

**Issue by skyhirider** [yaml/www.yaml.org#94]
https://snakeyaml.org/ seems to be a football page, I presume it used to be the website for the snakeyaml project?

I searched for the official page for snakeyaml but was not able to find it, old page on bitbucket is inaccessible and something called snakeyaml-engine is in the top results, but its version two instead of 1 that is found on maven.

Really confused overall.

**Comment by ingydotnet** [comment]
@skyhirider thanks for the find. I've made changes to the site. Let me know if it looks ok to you.

Cheers, Ingy  
https://matrix.to/#/#chat:yaml.io

**Comment by skyhirider** [comment]
@ingydotnet you could link to the official repo https://bitbucket.org/snakeyaml/snakeyaml or the GitHub mirror https://github.com/snakeyaml/snakeyaml

Snakeyaml engine is also there, the link you added is too another repo

https://bitbucket.org/snakeyaml/snakeyaml-engine/src/master/

I had the same issue when googling for the source and had to email the library maintainers. It's why I suggested an update to the links add others might have the same problem

**Comment by ingydotnet** [comment]
Fixed. Thanks for looking into that.

BTW, if you are a Java programmer we could use some help writing a (likely tiny) program that would add snakeyaml-engine to our multi language/framework parser testing. See https://matrix.yaml.io/

Find me on https://matrix.to/#/#chat:yaml.io and I can tell you more.
